<?php
return [
    [
        'menu_name' => '首页',
        'menu_key' => 'overview',
        'menu_short_name' => '首页',
        'parent_key' => '',
        'menu_type' => '1',
        'icon' => 'iconfont iconshouyec',
        'api_url' => '',
        'router_path' => 'index',
        'view_path' => 'index/index',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '统计数据',
                'menu_key' => 'admin_index_stat',
                'menu_short_name' => '统计数据',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'stat/index',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ]
        ]
    ],
    [
        'menu_name' => '系统设置',
        'menu_key' => 'setting_manage',
        'menu_short_name' => '配置',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'iconfont iconshezhi2',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '90',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '网站设置',
                'menu_key' => 'website_setting',
                'menu_short_name' => '网站设置',
                'menu_type' => '0',
                'icon' => 'iconfont iconwangzhanshezhic',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '80',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '基础设置',
                        'menu_key' => 'base_setting',
                        'menu_short_name' => '基础设置',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjichushezhic',
                        'api_url' => 'sys/config/website',
                        'router_path' => 'setting/website/system',
                        'view_path' => 'setting/system',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '保存',
                                'menu_key' => 'save_base_setting',
                                'menu_short_name' => '保存',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'sys/config/website',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '1',
                            ]
                        ]
                    ],
                    [
                        'menu_name' => '版权设置',
                        'menu_key' => 'setting_copyright',
                        'menu_short_name' => '版权设置',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconbanquanshezhic',
                        'api_url' => 'sys/config/copyright',
                        'router_path' => 'setting/website/copyright',
                        'view_path' => 'setting/copyright',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '保存',
                                'menu_key' => 'save_setting_copyright',
                                'menu_short_name' => '保存',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'sys/config/copyright',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '1',
                            ]
                        ]
                    ],
                ],
            ],
            [
                'menu_name' => '权限设置',
                'menu_key' => 'auth',
                'menu_short_name' => '权限设置',
                'menu_type' => '0',
                'icon' => 'iconfont iconquanxianshezhic',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '75',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '管理员列表',
                        'menu_key' => 'auth_list',
                        'menu_short_name' => '管理员列表',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconguanliyuanc',
                        'api_url' => 'site/user',
                        'router_path' => 'setting/auth/user',
                        'view_path' => 'auth/user',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '管理员信息',
                                'menu_key' => 'auth_user_detail',
                                'menu_short_name' => '管理员信息',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'site/user/<uid>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                            [
                                'menu_name' => '添加管理员',
                                'menu_key' => 'add_site_user',
                                'menu_short_name' => '添加管理员',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'site/user',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                            [
                                'menu_name' => '编辑管理员',
                                'menu_key' => 'edit_site_user',
                                'menu_short_name' => '编辑管理员',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'site/user/<uid>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                            [
                                'menu_name' => '修改管理员属性',
                                'menu_key' => 'edit_site_user_field',
                                'menu_short_name' => '修改管理员属性',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'site/user/<uid>/<field>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                            [
                                'menu_name' => '锁定',
                                'menu_key' => 'lock_site_user',
                                'menu_short_name' => '锁定',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'site/user/lock/<uid>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                            [
                                'menu_name' => '解锁',
                                'menu_key' => 'unlock_site_user',
                                'menu_short_name' => '解锁用户',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'site/user/unlock/<uid>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                            [
                                'menu_name' => '删除管理员',
                                'menu_key' => 'delete_site_user',
                                'menu_short_name' => '删除管理员',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'site/user/<uid>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '1',
                            ]
                        ]
                    ],
                    [
                        'menu_name' => '管理员角色',
                        'menu_key' => 'auth_role',
                        'menu_short_name' => '管理员角色',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconguanliyuanjiaosec',
                        'api_url' => 'sys/role',
                        'router_path' => 'setting/auth/role',
                        'view_path' => 'auth/role',
                        'methods' => 'get',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                        'children' => [
                            [
                                'menu_name' => '新增',
                                'menu_key' => 'auth_role_add',
                                'menu_short_name' => '新增',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'sys/role',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                            [
                                'menu_name' => '编辑',
                                'menu_key' => 'auth_role_update',
                                'menu_short_name' => '编辑',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'sys/role/<role_id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                            [
                                'menu_name' => '删除',
                                'menu_key' => 'auth_role_del',
                                'menu_short_name' => '删除',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'sys/role/<role_id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '操作日志',
                        'menu_key' => 'auth_log',
                        'menu_short_name' => '操作日志',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconcaozuorizhic',
                        'api_url' => 'sys/log',
                        'router_path' => 'setting/auth/log',
                        'view_path' => 'auth/log',
                        'methods' => 'get',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '存储设置',
                'menu_key' => 'setting_storage',
                'menu_short_name' => '存储设置',
                'menu_type' => '1',
                'icon' => 'iconfont iconcunchushezhic',
                'api_url' => 'sys/storage',
                'router_path' => 'setting/storage',
                'view_path' => 'setting/storage',
                'methods' => 'get',
                'sort' => '70',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '获取存储配置',
                        'menu_key' => 'setting_storage_value',
                        'menu_short_name' => '获取存储配置',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/storage/<storage_type>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '存储设置修改',
                        'menu_key' => 'edit_setting_storage',
                        'menu_short_name' => '存储设置修改',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/storage/<storage_type>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ]
                ]
            ],
            [
                'menu_name' => '登录设置',
                'menu_key' => 'setting_login',
                'menu_short_name' => '登录设置',
                'menu_type' => '1',
                'icon' => 'iconfont icondenglushezhic',
                'api_url' => 'sys/config/login',
                'router_path' => 'setting/adminlogin',
                'view_path' => 'setting/adminlogin',
                'methods' => 'get',
                'sort' => '65',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '保存',
                        'menu_key' => 'save_setting_login',
                        'menu_short_name' => '保存',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/config/login',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ]
                ]
            ],
            [
                'menu_name' => '微信开放平台',
                'menu_key' => 'wx_oplatform',
                'menu_short_name' => '微信开放平台',
                'menu_type' => '1',
                'icon' => 'iconfont iconweixinkaifangpingtaic',
                'api_url' => 'sys/config/wxoplatform',
                'router_path' => 'setting/oplatform',
                'view_path' => 'setting/oplatform',
                'methods' => 'get',
                'sort' => '60',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '保存',
                        'menu_key' => 'save_wxoplatform_config',
                        'menu_short_name' => '保存',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'wxoplatform/config',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '同步',
                        'menu_key' => 'commit_oplatform_weapp_version',
                        'menu_short_name' => '同步',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'wxoplatform/weapp/version/commit',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ]
                ]
            ],
            [
                'menu_name' => '素材管理',
                'menu_key' => 'attachment',
                'menu_short_name' => '素材管理',
                'menu_type' => '1',
                'icon' => 'iconfont iconsucaiguanlic',
                'api_url' => 'sys/attachment',
                'router_path' => 'setting/attachment',
                'view_path' => 'tools/attachment',
                'methods' => 'get',
                'sort' => '55',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '删除素材',
                        'menu_key' => 'delete_attachment',
                        'menu_short_name' => '删除素材',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/attachment/del',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '移动素材',
                        'menu_key' => 'move_attachment',
                        'menu_short_name' => '移动素材',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/attachment/batchmove',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '添加分组',
                        'menu_key' => 'add_attachment_category',
                        'menu_short_name' => '删除素材',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/attachment/category',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '添加分组',
                        'menu_key' => 'add_attachment_category',
                        'menu_short_name' => '添加分组',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/attachment/category',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '编辑分组',
                        'menu_key' => 'edit_attachment_category',
                        'menu_short_name' => '编辑分组',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/attachment/category/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '编辑分组',
                        'menu_key' => 'edit_attachment_category',
                        'menu_short_name' => '编辑分组',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/attachment/category/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ]
            ],
            [
                'menu_name' => '地图设置',
                'menu_key' => 'map_setting',
                'menu_short_name' => '地图设置',
                'menu_type' => '1',
                'icon' => 'iconfont iconditushezhic',
                'api_url' => 'sys/config/map',
                'router_path' => 'setting/map',
                'view_path' => 'setting/map',
                'methods' => 'get',
                'sort' => '50',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '保存',
                        'menu_key' => 'save_layout_setting',
                        'menu_short_name' => '保存',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/config/map',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ]
                ]
            ],
            [
                'menu_name' => '布局设置',
                'menu_key' => 'layout_setting',
                'menu_short_name' => '布局设置',
                'menu_type' => '1',
                'icon' => 'iconfont iconbujushezhic',
                'api_url' => 'sys/config/layout',
                'router_path' => 'setting/layout',
                'view_path' => 'setting/layout',
                'methods' => 'get',
                'sort' => '45',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '保存',
                        'menu_key' => 'save_layout_setting',
                        'menu_short_name' => '保存',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/config/layout',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ]
                ]
            ],
        ],
    ],
    [
        'menu_name' => '站点管理',
        'menu_key' => 'site_manage',
        'menu_short_name' => '站点',
        'parent_key' => '',
        'menu_type' => '1',
        'icon' => 'iconfont iconFramec-4',
        'api_url' => '',
        'router_path' => 'site/manage',
        'view_path' => 'site/manage',
        'methods' => '',
        'sort' => '80',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '添加站点',
                'menu_key' => 'add_site',
                'menu_short_name' => '添加站点',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'site/site',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '编辑站点',
                'menu_key' => 'edit_site',
                'menu_short_name' => '编辑站点',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'site/site/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '删除站点',
                'menu_key' => 'delete_site',
                'menu_short_name' => '删除站点',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'site/site/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'delete',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '关闭站点',
                'menu_key' => 'close_site',
                'menu_short_name' => '关闭站点',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'site/closesite/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '开启站点',
                'menu_key' => 'open_site',
                'menu_short_name' => '开启站点',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'site/opensite/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '删除站点套餐',
                'menu_key' => 'delete_site_group',
                'menu_short_name' => '删除站点套餐',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'site/group/<group_id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'delete',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
        ],
    ],
    [
        'menu_name' => '站点详情',
        'menu_key' => 'site_info',
        'menu_short_name' => '站点详情',
        'menu_type' => '1',
        'icon' => '',
        'api_url' => 'site/site/<site_id>',
        'router_path' => 'site/info',
        'view_path' => 'site/info',
        'methods' => 'get',
        'sort' => '90',
        'status' => '1',
        'is_show' => '0',
    ],
    [
        'menu_name' => '用户详情',
        'menu_key' => 'site_user_info',
        'menu_short_name' => '用户详情',
        'menu_type' => '1',
        'icon' => 'element OfficeBuilding',
        'api_url' => 'user/user/<uid>',
        'router_path' => 'site/user_info',
        'view_path' => 'site/user_info',
        'methods' => 'get',
        'sort' => '80',
        'status' => '1',
        'is_show' => '0',
    ],
    [
        'menu_name' => '站点套餐编辑',
        'menu_key' => 'site_group_edit',
        'menu_short_name' => '站点套餐编辑',
        'menu_type' => '1',
        'icon' => 'element PriceTag',
        'api_url' => '',
        'router_path' => 'site/group_edit',
        'view_path' => 'site/group_edit',
        'methods' => '',
        'sort' => '70',
        'status' => '1',
        'is_show' => '0',
        'children' => [
            [
                'menu_name' => '添加站点套餐',
                'menu_key' => 'add_site_group',
                'menu_short_name' => '添加站点套餐',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'site/group',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '编辑站点套餐',
                'menu_key' => 'edit_site_group',
                'menu_short_name' => '编辑站点套餐',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'site/group/<group_id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ]
        ]
    ],
    [
        'menu_name' => '用户管理',
        'menu_key' => 'site_user_list',
        'menu_short_name' => '用户',
        'menu_type' => '1',
        'icon' => 'iconfont iconyonghu11',
        'api_url' => 'user/user',
        'router_path' => 'site/user',
        'view_path' => 'site/user',
        'methods' => 'get',
        'sort' => '79',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '添加站点用户',
                'menu_key' => 'add_user',
                'menu_short_name' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'user/user',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '编辑站点用户',
                'menu_key' => 'edit_user',
                'menu_short_name' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'user/user/<uid>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '删除站点用户',
                'menu_key' => 'delete_user',
                'menu_short_name' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'user/user/<uid>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'delete',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '获取站点用户信息',
                'menu_key' => 'get_user_info',
                'menu_short_name' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'user/user/<uid>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '获取用户套餐权限',
                'menu_key' => 'get_user_create_site_limit',
                'menu_short_name' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'user/user/create_site_limit/<uid>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '获取用户套餐权限信息',
                'menu_key' => 'get_user_create_site_limit_info',
                'menu_short_name' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'user/user/create_site_limit/info/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '添加套餐权限',
                'menu_key' => 'add_user_create_site_limit',
                'menu_short_name' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'user/user/create_site_limit',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '编辑套餐权限',
                'menu_key' => 'edit_user_create_site_limit',
                'menu_short_name' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'user/user/create_site_limit/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '删除套餐权限',
                'menu_key' => 'del_user_create_site_limit',
                'menu_short_name' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'user/user/create_site_limit/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'delete',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
        ]
    ],
    [
        'menu_name' => '应用管理',
        'menu_key' => 'app_store',
        'menu_short_name' => '应用',
        'parent_key' => '',
        'menu_type' => '1',
        'icon' => 'iconfont iconFramec-5',
        'api_url' => 'addon/local',
        'router_path' => 'app_manage/app_store',
        'view_path' => 'index/store',
        'methods' => 'get',
        'sort' => '78',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '安装插件',
                'menu_key' => 'install_addon',
                'menu_short_name' => '安装插件',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'addon/install/<addon>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '插件卸载',
                'menu_key' => 'uninstall_addon',
                'menu_short_name' => '插件卸载',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'addon/uninstall/<addon>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '插件云安装',
                'menu_key' => 'cloud_install_addon',
                'menu_short_name' => '插件云安装',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'addon/cloudinstall/<addon>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '插件下载',
                'menu_key' => 'addon_download',
                'menu_short_name' => '插件下载',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'addon/download/<addon>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '云编译',
                'menu_key' => 'cloud_build',
                'menu_short_name' => '云编译按钮',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'niucloud/build',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '插件升级',
                'menu_key' => 'addon_upgrade',
                'menu_short_name' => '插件升级',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'upgrade/<addon>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ]
        ]
    ],
    [
        'menu_name' => '云编译',
        'menu_key' => 'cloud_compile',
        'menu_short_name' => '云编译',
        'menu_type' => '1',
        'icon' => 'iconfont iconyunbianyi',
        'api_url' => '',
        'router_path' => 'tools/cloud_compile',
        'view_path' => 'tools/cloud_compile',
        'methods' => 'post',
        'sort' => '0',
        'status' => '1',
        'is_show' => '1',
    ],
    [
        'menu_name' => '应用开发',
        'menu_key' => 'tool',
        'menu_short_name' => '开发',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'iconfont iconFramec-3',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '76',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '插件开发',
                'menu_key' => 'addon_expolit',
                'menu_short_name' => '插件开发',
                'menu_type' => '0',
                'icon' => 'iconfont iconchajiankaifa11',
                'api_url' => '',
                'router_path' => 'tools/addon/expolit',
                'view_path' => 'tools/addon/expolit',
                'methods' => 'get',
                'sort' => '108',
                'status' => '1',
                'is_show' => '1',
                'children' => [

                    [
                        'menu_name' => '开发步骤',
                        'menu_key' => 'addon_develop',
                        'menu_short_name' => '步骤',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconchajiankaifa11',
                        'api_url' => '',
                        'router_path' => 'tools/addon',
                        'view_path' => 'tools/addon/index',
                        'methods' => '',
                        'sort' => '111',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '插件列表',
                        'menu_key' => 'addon_list',
                        'menu_short_name' => '列表',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconchajiankaifa11',
                        'api_url' => '',
                        'router_path' => 'tools/addon/list',
                        'view_path' => 'tools/addon/list',
                        'methods' => '',
                        'sort' => '110',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '删除插件',
                                'menu_key' => 'delete_develop_addon',
                                'menu_short_name' => '删除插件',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'addon/addon_develop/<key>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                            [
                                'menu_name' => '打包插件',
                                'menu_key' => 'build_develop_addon',
                                'menu_short_name' => '打包插件',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'addon/addon_develop/build/<key>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '1',
                            ]
                        ]
                    ],
                    [
                        'menu_name' => '代码生成',
                        'menu_key' => 'code',
                        'menu_short_name' => '代码生成',
                        'menu_type' => '1',
                        'icon' => 'iconfont icondaimashengcheng11',
                        'api_url' => 'generator/generator',
                        'router_path' => 'tools/code',
                        'view_path' => 'tools/code/index',
                        'methods' => 'get',
                        'sort' => '109',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '生成列表',
                        'menu_key' => 'code_list',
                        'menu_short_name' => '生成列表',
                        'menu_type' => '1',
                        'icon' => 'iconfont icondaimashengcheng11',
                        'api_url' => 'generator/generator',
                        'router_path' => 'tools/code/list',
                        'view_path' => 'tools/code/list',
                        'methods' => 'get',
                        'sort' => '108',
                        'status' => '1',
                        'is_show' => '1',
                    ],

                    [
                        'menu_name' => '数据字典',
                        'menu_key' => 'sys_dict_dict_dict_list',
                        'menu_short_name' => '数据字典',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconshujuzidian1',
                        'api_url' => 'dict/post/post',
                        'router_path' => 'tools/list',
                        'view_path' => 'dict/list',
                        'methods' => 'get',
                        'sort' => '107',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '数据字典添加',
                                'menu_key' => 'sys_dict_dict_dict_add',
                                'menu_short_name' => '数据字典添加',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'dict',
                                'router_path' => 'edit',
                                'view_path' => 'dict/edit',
                                'methods' => 'post',
                                'sort' => '4',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                            [
                                'menu_name' => '编辑',
                                'menu_key' => 'sys_dict_dict_dict_edit',
                                'menu_short_name' => '编辑',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'dict/<id>',
                                'router_path' => 'edit',
                                'view_path' => 'dict/edit',
                                'methods' => 'put',
                                'sort' => '3',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                            [
                                'menu_name' => '删除',
                                'menu_key' => 'sys_dict_dict_dict_delete',
                                'menu_short_name' => '删除',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'dict/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '2',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '开发者key',
                        'menu_key' => 'developer_token',
                        'menu_short_name' => '开发者key',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconkaifazhekry',
                        'api_url' => 'sys/config/developer_token',
                        'router_path' => 'tools/developer_token',
                        'view_path' => 'setting/developer_token',
                        'methods' => 'get',
                        'sort' => '97',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '保存',
                                'menu_key' => 'save_developer_token',
                                'menu_short_name' => '同步',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'sys/config/developer_token',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '1',
                            ]
                        ]
                    ],
                ]
            ],
            [
                'menu_name' => '更新缓存',
                'menu_key' => 'update_cache',
                'menu_short_name' => '更新缓存',
                'menu_type' => '1',
                'icon' => 'iconfont icongengxinhuancun2',
                'api_url' => 'sys/schema/clear',
                'router_path' => 'tools/update_cache',
                'view_path' => 'tools/updatecache',
                'methods' => 'post',
                'sort' => '108',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '数据表编辑',
                'menu_key' => 'code_edit',
                'menu_short_name' => '数据表编辑',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'tools/code/edit',
                'view_path' => 'tools/code/edit',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '添加数据表',
                        'menu_key' => 'add_generator',
                        'menu_short_name' => '添加数据表',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'generator/generator',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '编辑数据表',
                        'menu_key' => 'edit_generator',
                        'menu_short_name' => '编辑数据表',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'generator/generator/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '删除数据表',
                        'menu_key' => 'delete_generator',
                        'menu_short_name' => '删除数据表',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'generator/generator/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '代码生成',
                        'menu_key' => 'generator_download',
                        'menu_short_name' => '代码生成',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'generator/download',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ]
                ]
            ],
            [
                'menu_name' => '插件添加/编辑',
                'menu_key' => 'addon_edit',
                'menu_short_name' => '插件添加/编辑',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'tools/addon_edit',
                'view_path' => 'tools/addon/edit',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '添加插件',
                        'menu_key' => 'add_develop_addon',
                        'menu_short_name' => '添加插件',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'addon/addon_develop/<key>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '编辑插件',
                        'menu_key' => 'edit_develop_addon',
                        'menu_short_name' => '编辑插件',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'addon/addon_develop/<key>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ]
            ],
            [
                'menu_name' => '平台菜单',
                'menu_key' => 'platform_menu',
                'menu_short_name' => '平台菜单',
                'menu_type' => '1',
                'icon' => 'iconfont iconpingtaicaidan1',
                'api_url' => 'sys/menu',
                'router_path' => 'tools/admin_menu',
                'view_path' => 'auth/menu',
                'methods' => 'get',
                'sort' => '105',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '新增',
                        'menu_key' => 'auth_menu_add',
                        'menu_short_name' => '新增',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/menu',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '编辑',
                        'menu_key' => 'auth_menu_update',
                        'menu_short_name' => '编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/menu/<menu_key>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '删除',
                        'menu_key' => 'auth_menu_del',
                        'menu_short_name' => '删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/menu',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '详情',
                        'menu_key' => 'auth_menu_info',
                        'menu_short_name' => '详情',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/menu/<menu_key>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '站点菜单',
                'menu_key' => 'site_menu',
                'menu_short_name' => '站点菜单',
                'menu_type' => '1',
                'icon' => 'iconfont iconzhandiancaidan1',
                'api_url' => 'sys/menu',
                'router_path' => 'tools/site_menu',
                'view_path' => 'auth/site_menu',
                'methods' => 'get',
                'sort' => '104',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '新增',
                        'menu_key' => 'auth_site_menu_add',
                        'menu_short_name' => '新增',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/menu',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '编辑',
                        'menu_key' => 'auth_site_menu_update',
                        'menu_short_name' => '编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/menu/<menu_key>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '删除',
                        'menu_key' => 'auth_site_menu_del',
                        'menu_short_name' => '删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/menu',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '详情',
                        'menu_key' => 'auth_site_menu_info',
                        'menu_short_name' => '详情',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/menu/<menu_key>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '计划任务',
                'menu_key' => 'tools_schedule',
                'menu_short_name' => '计划任务',
                'menu_type' => '1',
                'icon' => 'iconfont iconjihuarenwu11',
                'api_url' => 'sys/schedule/list',
                'router_path' => 'tools/schedule',
                'view_path' => 'tools/schedule',
                'methods' => '',
                'sort' => '103',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '新增',
                        'menu_key' => 'schedule_add',
                        'menu_short_name' => '新增',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/schedule',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '4',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '编辑',
                        'menu_key' => 'schedule_update',
                        'menu_short_name' => '编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/schedule/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '3',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '设置状态',
                        'menu_key' => 'schedule_set_status',
                        'menu_short_name' => '设置状态',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'schedule/modify/status/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '2',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '删除',
                        'menu_key' => 'schedule_del',
                        'menu_short_name' => '删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/schedule/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '环境检测',
                'menu_key' => 'tools_check_environment',
                'menu_short_name' => '环境检测',
                'menu_type' => '1',
                'icon' => 'iconfont iconhuanjingjiance11',
                'api_url' => '',
                'router_path' => 'tools/detection',
                'view_path' => 'tools/detection',
                'methods' => '',
                'sort' => '102',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '执行日志',
                'menu_key' => 'tools_schedule_log',
                'menu_short_name' => '执行日志',
                'menu_type' => '1',
                'icon' => 'iconfont iconjihuarenwu',
                'api_url' => 'sys/schedule/log/list',
                'router_path' => 'tools/schedule_log',
                'view_path' => 'tools/schedule_log',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0'
            ],
            [
                'menu_name' => '备份升级',
                'menu_key' => 'backup_upgrade',
                'menu_short_name' => '备份升级',
                'menu_type' => '1',
                'icon' => 'iconfont iconbeifenjilu',
                'api_url' => '',
                'router_path' => 'tools/backup_upgrade',
                'view_path' => 'tools/backup_upgrade',
                'methods' => 'get',
                'sort' => '99',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '升级记录',
                        'menu_key' => 'upgrade_records',
                        'menu_short_name' => '升级记录',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconshengjijilu1',
                        'api_url' => 'upgrade/records',
                        'router_path' => 'tools/upgrade_records',
                        'view_path' => 'tools/upgrade_records',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '备份记录',
                        'menu_key' => 'backup_records',
                        'menu_short_name' => '备份记录',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconbeifenjilu',
                        'api_url' => 'backup/records',
                        'router_path' => 'tools/backup_records',
                        'view_path' => 'tools/backup_records',
                        'methods' => 'post',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ]
            ],
            [
                'menu_name' => '授权信息',
                'menu_key' => 'app_auth',
                'menu_short_name' => '授权信息',
                'menu_type' => '1',
                'icon' => 'iconfont iconshouquanxinxi1',
                'api_url' => '',
                'router_path' => 'tools/authorize',
                'view_path' => 'app/authorize',
                'methods' => '',
                'sort' => '98',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '绑定授权信息',
                        'menu_key' => 'bind_app_auth',
                        'menu_short_name' => '绑定授权信息',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'niucloud/authinfo',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ]
                ]
            ],
            [
                'menu_name' => '系统更新',
                'menu_key' => 'system_upgrade',
                'menu_short_name' => '系统更新',
                'menu_type' => '1',
                'icon' => 'iconfont iconxitonggengxin1',
                'api_url' => '',
                'router_path' => 'tools/upgrade',
                'view_path' => 'app/upgrade',
                'methods' => '',
                'sort' => '97',
                'status' => '1',
                'is_show' => '1',
            ],
        ],
    ],

];
