<?php
return [
    [
        'menu_name' => '理发店预约系统',
        'menu_key' => 'zzhc',
        'menu_short_name' => '理发',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'zzhc icon-tongji',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '数据概况',
                'menu_key' => 'zzhc_index',
                'menu_short_name' => '概况',
                'menu_type' => '1',
                'icon' => 'zzhc icon-tongji',
                'api_url' => 'zzhc/index',
                'router_path' => 'index',
                'view_path' => 'index',
                'methods' => 'get',
                'sort' => '888',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '门店管理',
                'menu_key' => 'zzhc_zzhc_store_store_store',
                'menu_short_name' => '门店',
                'menu_type' => '0',
                'icon' => 'zzhc icon-mendian',
                'api_url' => '',
                'router_path' => 'store',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '门店列表',
                        'menu_key' => 'zzhc_zzhc_store_store_store_list',
                        'menu_short_name' => '门店列表',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/store',
                        'router_path' => 'store/store',
                        'view_path' => 'store/store',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '门店添加',
                        'menu_key' => 'zzhc_zzhc_store_store_store_add',
                        'menu_short_name' => '门店添加',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/store',
                        'router_path' => 'store/store_edit',
                        'view_path' => 'store/store_edit',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '门店编辑',
                        'menu_key' => 'zzhc_zzhc_store_store_store_edit',
                        'menu_short_name' => '门店编辑',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/store/<id>',
                        'router_path' => 'store/store_edit',
                        'view_path' => 'store/store_edit',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '门店删除',
                        'menu_key' => 'zzhc_zzhc_store_store_store_delete',
                        'menu_short_name' => '门店删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'zzhc/store/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '员工管理',
                'menu_key' => 'zzhc_zzhc_staff_staff_staff',
                'menu_short_name' => '员工',
                'menu_type' => '0',
                'icon' => 'zzhc icon-yuangong',
                'api_url' => '',
                'router_path' => 'staff',
                'view_path' => '',
                'methods' => '',
                'sort' => '99',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '员工列表',
                        'menu_key' => 'zzhc_zzhc_staff_staff_staff_list',
                        'menu_short_name' => '员工列表',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/staff',
                        'router_path' => 'staff/staff',
                        'view_path' => 'staff/staff',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '考勤记录',
                        'menu_key' => 'zzhc_zzhc_staff_work_staff_work',
                        'menu_short_name' => '考勤记录',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/work',
                        'router_path' => 'staff/work',
                        'view_path' => 'staff/work',
                        'methods' => 'get',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '考勤管理添加',
                                'menu_key' => 'zzhc_zzhc_staff_work_staff_work_add',
                                'menu_short_name' => '考勤管理添加',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/work',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '70',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '考勤管理编辑',
                                'menu_key' => 'zzhc_zzhc_staff_work_staff_work_edit',
                                'menu_short_name' => '考勤管理编辑',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/work/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '60',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '考勤管理删除',
                                'menu_key' => 'zzhc_zzhc_staff_work_staff_work_delete',
                                'menu_short_name' => '考勤管理删除',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/work/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '50',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '员工添加',
                        'menu_key' => 'zzhc_zzhc_staff_staff_staff_add',
                        'menu_short_name' => '员工添加',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/staff',
                        'router_path' => 'staff/staff_edit',
                        'view_path' => 'staff/staff_edit',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '员工编辑',
                        'menu_key' => 'zzhc_zzhc_staff_staff_staff_edit',
                        'menu_short_name' => '员工编辑',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/staff/<id>',
                        'router_path' => 'staff/staff_edit',
                        'view_path' => 'staff/staff_edit',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '员工删除',
                        'menu_key' => 'zzhc_zzhc_staff_staff_staff_delete',
                        'menu_short_name' => '员工删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'zzhc/staff/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '项目管理',
                'menu_key' => 'zzhc_zzhc_goods_category_goods_category',
                'menu_short_name' => '项目',
                'menu_type' => '0',
                'icon' => 'zzhc icon-xiangmuguanli',
                'api_url' => '',
                'router_path' => 'goods',
                'view_path' => '',
                'methods' => '',
                'sort' => '98',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '项目列表',
                        'menu_key' => 'zzhc_zzhc_goods_goods_goods',
                        'menu_short_name' => '项目',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/goods',
                        'router_path' => 'goods/goods',
                        'view_path' => 'goods/goods',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '项目添加',
                                'menu_key' => 'zzhc_zzhc_goods_goods_goods_add',
                                'menu_short_name' => '项目添加',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/goods',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '70',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '项目编辑',
                                'menu_key' => 'zzhc_zzhc_goods_goods_goods_edit',
                                'menu_short_name' => '项目编辑',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/goods/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '60',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '项目删除',
                                'menu_key' => 'zzhc_zzhc_goods_goods_goods_delete',
                                'menu_short_name' => '项目删除',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/goods/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '50',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '分类管理',
                        'menu_key' => 'zzhc_zzhc_goods_category_goods_category_list',
                        'menu_short_name' => '项目分类列表',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/category',
                        'router_path' => 'goods/category',
                        'view_path' => 'goods/category',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '项目分类添加',
                        'menu_key' => 'zzhc_zzhc_goods_category_goods_category_add',
                        'menu_short_name' => '项目分类添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'zzhc/category',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '项目分类编辑',
                        'menu_key' => 'zzhc_zzhc_goods_category_goods_category_edit',
                        'menu_short_name' => '项目分类编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'zzhc/category/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '项目分类删除',
                        'menu_key' => 'zzhc_zzhc_goods_category_goods_category_delete',
                        'menu_short_name' => '项目分类删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'zzhc/category/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '订单管理',
                'menu_key' => 'zzhc_zzhc_order_order_order',
                'menu_short_name' => '订单',
                'menu_type' => '0',
                'icon' => 'zzhc icon-dingdan1',
                'api_url' => '',
                'router_path' => 'order',
                'view_path' => '',
                'methods' => '',
                'sort' => '97',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '预约订单',
                        'menu_key' => 'zzhc_zzhc_order_order_order_list',
                        'menu_short_name' => '预约订单',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/order',
                        'router_path' => 'order/order',
                        'view_path' => 'order/order',
                        'methods' => 'get',
                        'sort' => '200',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '办卡订单',
                        'menu_key' => 'zzhc_zzhc_vip_order_vip_order',
                        'menu_short_name' => '办卡订单',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/order',
                        'router_path' => 'vip/order',
                        'view_path' => 'vip/order',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '办卡订单添加',
                                'menu_key' => 'zzhc_zzhc_vip_order_vip_order_add',
                                'menu_short_name' => '办卡订单添加',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/order',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '70',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '办卡订单编辑',
                                'menu_key' => 'zzhc_zzhc_vip_order_vip_order_edit',
                                'menu_short_name' => '办卡订单编辑',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/order/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '60',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '办卡订单删除',
                                'menu_key' => 'zzhc_zzhc_vip_order_vip_order_delete',
                                'menu_short_name' => '办卡订单删除',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/order/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '50',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '预约订单删除',
                        'menu_key' => 'zzhc_zzhc_order_order_order_delete',
                        'menu_short_name' => '预约订单删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'zzhc/order/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '预约订单详情',
                        'menu_key' => 'zzhc_order_order_detail',
                        'menu_short_name' => '预约订单详情',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/order/<id>',
                        'router_path' => 'order/order_detail',
                        'view_path' => 'order/order_detail',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '卡券管理',
                'menu_key' => 'zzhc_zzhc_vip_marketing_vip',
                'menu_short_name' => '卡券',
                'menu_type' => '0',
                'icon' => 'zzhc icon-kaquanbao',
                'api_url' => '',
                'router_path' => 'marketing',
                'view_path' => '',
                'methods' => '',
                'sort' => '96',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '办卡会员',
                        'menu_key' => 'zzhc_zzhc_vip_member_vip_member',
                        'menu_short_name' => '办卡会员',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/vip_member',
                        'router_path' => 'vip/member',
                        'view_path' => 'vip/member',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '办卡会员添加',
                                'menu_key' => 'zzhc_zzhc_vip_member_vip_member_add',
                                'menu_short_name' => '办卡会员添加',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/member',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '70',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '办卡会员编辑',
                                'menu_key' => 'zzhc_zzhc_vip_member_vip_member_edit',
                                'menu_short_name' => '办卡会员编辑',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/member/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '60',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '办卡会员删除',
                                'menu_key' => 'zzhc_zzhc_vip_member_vip_member_delete',
                                'menu_short_name' => '办卡会员删除',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/member/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '50',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '会员优惠券',
                        'menu_key' => 'zzhc_zzhc_coupon_member_coupon_member',
                        'menu_short_name' => '会员优惠券',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/coupon_member',
                        'router_path' => 'coupon/member',
                        'view_path' => 'coupon/member',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '领券记录添加',
                                'menu_key' => 'zzhc_zzhc_coupon_member_coupon_member_add',
                                'menu_short_name' => '领券记录添加',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/member',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '70',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '领券记录编辑',
                                'menu_key' => 'zzhc_zzhc_coupon_member_coupon_member_edit',
                                'menu_short_name' => '领券记录编辑',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/member/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '60',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '领券记录删除',
                                'menu_key' => 'zzhc_zzhc_coupon_member_coupon_member_delete',
                                'menu_short_name' => '领券记录删除',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/member/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '50',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '优惠券管理',
                        'menu_key' => 'zzhc_zzhc_coupon_marketing_coupon',
                        'menu_short_name' => '优惠券',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/coupon',
                        'router_path' => 'coupon/coupon',
                        'view_path' => 'coupon/coupon',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '优惠券添加',
                                'menu_key' => 'zzhc_zzhc_coupon_marketing_coupon_add',
                                'menu_short_name' => '优惠券添加',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/coupon',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '70',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '优惠券编辑',
                                'menu_key' => 'zzhc_zzhc_coupon_marketing_coupon_edit',
                                'menu_short_name' => '优惠券编辑',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/coupon/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '60',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '优惠券删除',
                                'menu_key' => 'zzhc_zzhc_coupon_marketing_coupon_delete',
                                'menu_short_name' => '优惠券删除',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'zzhc/coupon/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '50',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '会员卡套餐',
                        'menu_key' => 'zzhc_zzhc_vip_marketing_vip_list',
                        'menu_short_name' => '会员卡管理',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'zzhc/vip',
                        'router_path' => 'vip/vip',
                        'view_path' => 'vip/vip',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => 'VIP套餐添加',
                        'menu_key' => 'zzhc_zzhc_vip_marketing_vip_add',
                        'menu_short_name' => 'VIP套餐添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'zzhc/vip',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => 'VIP套餐编辑',
                        'menu_key' => 'zzhc_zzhc_vip_marketing_vip_edit',
                        'menu_short_name' => 'VIP套餐编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'zzhc/vip/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => 'VIP套餐删除',
                        'menu_key' => 'zzhc_zzhc_vip_marketing_vip_delete',
                        'menu_short_name' => 'VIP套餐删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'zzhc/vip/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '会员卡配置',
                        'menu_key' => 'zzhc_marketing_vip_config',
                        'menu_short_name' => '会员卡配置',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'vip/vip_config',
                        'view_path' => 'vip/vip_config',
                        'methods' => 'post',
                        'sort' => '40',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
        ],
    ],
];