<?php
return [
    [
        "name" => "找朋友帮忙付模板", // 海报模板名称
        'type' => 'friendspay', // 海报类型
        "data" => [
            "global" => [
                "width" => 720,
                "height" => 1280,
                "bgType" => "url",
                "bgColor" => "#ffffff",
                "bgUrl" => "static/resource/images/pay/friendspay_bg.jpg"
            ],
            "value" => [
                [
                    "type" => "text",
                    "path" => "text",
                    "uses" => 0,
                    "relate" => "",
                    "value" => "您的帮付金额",
                    "id" => "wgvspr9fafk",
                    "componentName" => "Text",
                    "componentTitle" => "文本",
                    "width" => 518,
                    "height" => 48,
                    "minWidth" => 120,
                    "minHeight" => 44,
                    "x" => "center",
                    "y" => 759,
                    "angle" => 0,
                    "zIndex" => 8,
                    "fontFamily" => "static/font/SourceHanSansCN-Regular.ttf",
                    "fontSize" => 24,
                    "weight" => false,
                    "lineHeight" => 20,
                    "fontColor" => "#333333"
                ],
                [
                    "type" => "text",
                    "path" => "friendspay-money",
                    "uses" => 1,
                    "relate" => "friendspay_money",
                    "value" => "￥369.00",
                    "id" => "2waud25nthq0",
                    "componentName" => "FriendsPayMoney",
                    "componentTitle" => "帮付金额",
                    "width" => 518,
                    "height" => 58,
                    "minWidth" => 120,
                    "minHeight" => 44,
                    "x" => "center",
                    "y" => 694,
                    "angle" => 0,
                    "zIndex" => 9,
                    "fontFamily" => "static/font/price.ttf",
                    "fontSize" => 56,
                    "weight" => false,
                    "lineHeight" => 10,
                    "fontColor" => "#FF4142"
                ],
                [
                    "type" => "text",
                    "path" => "text",
                    "uses" => 0,
                    "relate" => "",
                    "value" => "长按识别二维码，帮我付款",
                    "id" => "639vjo8ebo40",
                    "componentName" => "Text",
                    "componentTitle" => "文本",
                    "width" => 518,
                    "height" => 59,
                    "minWidth" => 120,
                    "minHeight" => 44,
                    "x" => "center",
                    "y" => 1097,
                    "angle" => 0,
                    "zIndex" => 10,
                    "fontFamily" => "static/font/SourceHanSansCN-Regular.ttf",
                    "fontSize" => 26,
                    "weight" => false,
                    "lineHeight" => 26,
                    "fontColor" => "#333333"
                ],
                [
                    "type" => "text",
                    "path" => "friendspay-message",
                    "uses" => 1,
                    "relate" => "friendspay_message",
                    "value" => "帮我付一下这笔订单吧，谢谢啦~",
                    "id" => "5oyikcgoylo0",
                    "componentName" => "FriendsPayMessage",
                    "componentTitle" => "帮付留言",
                    "width" => 600,
                    "height" => 48,
                    "minWidth" => 120,
                    "minHeight" => 44,
                    "x" => "center",
                    "y" => 570,
                    "angle" => 0,
                    "zIndex" => 4,
                    "fontFamily" => "static/font/SourceHanSansCN-Regular.ttf",
                    "fontSize" => 26,
                    "weight" => false,
                    "lineHeight" => 10,
                    "fontColor" => "#666666"
                ],
                [
                    "type" => "qrcode",
                    "path" => "qrcode",
                    "uses" => 1,
                    "relate" => "url",
                    "value" => "",
                    "id" => "3m6szk6d98m0",
                    "componentName" => "Qrcode",
                    "componentTitle" => "二维码",
                    "width" => 214,
                    "height" => 214,
                    "minWidth" => 60,
                    "minHeight" => 60,
                    "x" => 254,
                    "y" => 844,
                    "angle" => 0,
                    "zIndex" => 8
                ],
                [
                    "type" => "text",
                    "path" => "nickname",
                    "uses" => 1,
                    "relate" => "nickname",
                    "value" => "",
                    "id" => "31wsjudfc7m0",
                    "componentName" => "NickName",
                    "componentTitle" => "昵称",
                    "width" => 600,
                    "height" => 40,
                    "minWidth" => 120,
                    "minHeight" => 50,
                    "x" => "center",
                    "y" => 512,
                    "angle" => 0,
                    "zIndex" => 6,
                    "fontFamily" => "static/font/SourceHanSansCN-Regular.ttf",
                    "fontSize" => 30,
                    "weight" => false,
                    "lineHeight" => 10,
                    "fontColor" => "#303133"
                ],
                [
                    "type" => "image",
                    "path" => "headimg",
                    "uses" => 1,
                    "relate" => "headimg",
                    "value" => "",
                    "id" => "5asgzwz9f5s0",
                    "componentName" => "HeadImg",
                    "componentTitle" => "头像",
                    "width" => 149,
                    "height" => 149,
                    "minWidth" => 60,
                    "minHeight" => 60,
                    "x" => 286,
                    "y" => 344,
                    "angle" => 0,
                    "zIndex" => 7,
                    "shape" => "circle"
                ]
            ]
        ]
    ],
];